name: bridge_cav_01

topics:
  /Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 1
    to_domain: 100
    remap: /CAV_01

  /CAV_01/cmd_stop:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 1
    remap: /cmd_stop

  /CAV_01/change_waypoint:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 1
    remap: /change_waypoint

  /CAV_01/is_roundabout:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 1
    remap: /is_roundabout

  /CAV_01/hv_vel:
    type: std_msgs/msg/Float32
    from_domain: 100
    to_domain: 1
    remap: /hv_vel
