name: bridge_cav_06

topics:
  /Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 6
    to_domain: 100
    remap: /CAV_06

  /CAV_06/cmd_stop:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 6
    remap: /cmd_stop

  /CAV_06/change_waypoint:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 6
    remap: /change_waypoint

  /CAV_06/is_roundabout:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 6
    remap: /is_roundabout

  /CAV_06/hv_vel:
    type: std_msgs/msg/Float32
    from_domain: 100
    to_domain: 6
    remap: /hv_vel
