name: bridge_cav_04

topics:
  /Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 4
    to_domain: 100
    remap: /CAV_04

  /CAV_04/cmd_stop:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 4
    remap: /cmd_stop

  /CAV_04/change_waypoint:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 4
    remap: /change_waypoint

  /CAV_04/is_roundabout:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 4
    remap: /is_roundabout

  /CAV_04/hv_vel:
    type: std_msgs/msg/Float32
    from_domain: 100
    to_domain: 4
    remap: /hv_vel
