name: bridge_role_02
from_domain: 9    # <--- [당일 수정] 실제 내 차량 도메인 ID 입력
to_domain: 100

topics:
  # 1. 차량 -> 관제탑
  /CAV_02/Ego_pose:
    type: geometry_msgs/msg/PoseStamped
  
  /CAV_02/change_waypoint:
    type: std_msgs/msg/Bool

  # 2. 관제탑 -> 차량 (역방향)
  # [당일 수정] to_domain 값을 실제 내 차량 ID로 변경!
  /CAV_02/cmd_stop:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 9

  /CAV_02/hv_vel:
    type: std_msgs/msg/Float32
    from_domain: 100
    to_domain: 9

  /CAV_02/is_roundabout:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 9