name: bridge_role_01
from_domain: 27   # <--- [당일 수정] 실제 내 차량 도메인 ID 입력
to_domain: 100    # 관제탑 도메인 (고정)

topics:
  # 1. 차량 -> 관제탑 (정방향: 내 도메인 -> 100)
  /CAV_01/Ego_pose:
    type: geometry_msgs/msg/PoseStamped
  
  /CAV_01/change_waypoint:
    type: std_msgs/msg/Bool

  # 2. 관제탑 -> 차량 (역방향: 100 -> 내 도메인)
  # [당일 수정] to_domain 값을 실제 내 차량 ID로 바꿔야 함!
  /CAV_01/cmd_stop:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 27

  /CAV_01/hv_vel:
    type: std_msgs/msg/Float32
    from_domain: 100
    to_domain: 27

  /CAV_01/is_roundabout:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 27